[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  framework = "create-react-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
